---
services:
  db:
    image: srivardhan22/pyproj:db_image
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynet

  auth_service:
    image: srivardhan22/pyproj:auth_image
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynet
    depends_on:
      - db

  book_service:
    image: srivardhan22/pyproj:book_image
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynet
    depends_on:
      - db

  borrow_service:
    image: srivardhan22/pyproj:borrow_image
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynet
    depends_on:
      - db

  frontend:
    image: srivardhan22/pyproj:frontend
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynet
    depends_on:
      - auth_service
      - book_service
      - borrow_service

networks:
  mynet:
    driver: overlay
